#Database
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/kyn_db
        username: root
        password: 
        driver-class-name: com.mysql.jdbc.Driver
    jpa: 
        hibernate: 
            ddl-auto: update
        properties: 
            hibernate: 
                dialect: org.hibernate.dialect.MySQL8Dialect
    
    security:
        oauth2:
          client:
            registration:
                google:
                  clientId: 
                  clientSecret: 
                  redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
                  scope:
                      - email
                      - profile
app:
  auth:
    tokenSecret: 7Q8R9TBUCVEXFYG2J3K4M6P7Q8M5N6Q8R9SBUCVDXFYGZH3K4M5P2J3M5N6P8R9SAUCVDWEYGZH2K4FYH2J3K5N6P7Q9SATBVDWEXGZHVEXFYG2J3K4M6P7Q8SATBUDWEX
    tokenExpirationMsec: 864000000
  cors:
    allowedOrigins: http://localhost:3000, http://localhost:8080
  oauth2:
    # redirection uri
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
